spring.application.name=account
server.port=8080

#spring.datasource.url= jdbc:postgresql://localhost:5438/account_service #local database
#spring.datasource.url= jdbc:postgresql://postgres:5438/account_service #docker database
#spring.datasource.username= account
#spring.datasource.password= account123

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

# ======== Config Server =======
spring.profiles.active=prod
#spring.config.import=configserver:http://localhost:8071
spring.config.import=optional:configserver:http://configserver:8071

spring.jpa.hibernate.ddl-auto= update

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#======== Shut Down Service Config =========
management.endpoint.shutdown.enabled=true

# ====== Eureka Register  =======
eureka.instance.preferIpAddress=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone= http://localhost:9000/eureka/

# ======== Actuator =======
management.endpoints.web.exposure.include=*

management.health.liveness-state.enabled=true
management.health.readiness-state.enabled=true
management.endpoint.health.probes.enabled=true

# ======== Metrics =======
management.metrics.tags.application=${spring.application.name}

# ======== Spring Rabbit MQ =======
spring.cloud.function.definition=updateCustomerCommunication
spring.cloud.stream.bindings.sendCommunication-out-0.destination=send-communication
spring.cloud.stream.bindings.updateCustomerCommunication-in-0.destination=communication-send
spring.cloud.stream.bindings.updateCustomerCommunication-in-0.group=${spring.application.name}

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.connection-timeout=10s

# ======== Kafka =========
spring.cloud.stream.kafka.binder.brokers=localhost:9092,localhost:9094,localhost:9096
#spring.cloud.stream.kafka.binder.brokers=kafka-1:9092,kafka-2:9094,kafka-3:9096

# ======== configuring info endpoint =========
info.app.name = Account Microservice
info.app.description = Piseth Bank Account App
info.app.version = 1.0.0
management.info.env.enabled = true

# ======== CircuitBreaker =========
resilience4j.circuitbreaker.config.default.registerHealthIndicator= true
resilience4j.circuitbreaker.instances.customerDetailSupport.minimumNumberOfCalls= 5
resilience4j.circuitbreaker.instances.customerDetailSupport.failureRateThreshold= 50
resilience4j.circuitbreaker.instances.customerDetailSupport.waitDurationInOpenState= 30000
resilience4j.circuitbreaker.instances.customerDetailSupport.permittedNumberOfCallsInHalfOpenState= 2

# ======== Retry Pattern =========
resilience4j.retry.config.default.registerHealthIndicator=true
resilience4j.retry.config.instance.retryCustomerDetail.maxRetryAttempts=3
resilience4j.retry.config.instance.retryCustomerDetail.waitDuration=2000

# ======== Rate Limit Pattern =========
resilience4j.ratelimiter.config.default.registerHealthIndicator=true
resilience4j.ratelimiter.instance.sayHelloLimiter.timeoutDuration=10000
resilience4j.ratelimiter.instance.sayHelloLimiter.limitRefreshPeriod=10000
resilience4j.ratelimiter.instance.sayHelloLimiter.limitForPeriod=1

#====== log debug =============
logging.level.com.piseth.bank.account=DEBUG

#========= Open Telemetry ==============
logging.pattern.level="%5p [${spring.application.name},%X{trace_id},%X{span_id}]"