version: "3.8"
services:
  configserver:
    image: pisethbank/configserver:latest
    mem_limit: 700m
    ports:
      - "8000:8071"
    networks:
      - pisethbanknet
    
  eurekaserver:
    image: pisethbank/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - pisethbanknet
    depends_on:
      - configserver
    deploy: 
      restart_policy:
        condition: on-failure
        delay: 35s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
  mongodb-eureka:
    image: mongo:latest
    ports:
      - "7777:27017"
    networks:
      - pisethbanknet
  account:
    image: pisethbank/account:latest
    mem_limit: 700m
    ports:
      - "7000:8080"
    networks:
      - pisethbanknet
    depends_on:
      - configserver
      - eurekaserver
      - mongodb-eureka
    deploy: 
      restart_policy:
        condition: on-failure
        delay: 35s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9000/eureka/
  loan:
    image: pisethbank/loan:latest
    mem_limit: 700m
    ports:
      - "6000:8090"
    networks:
      - pisethbanknet
    depends_on:
      - configserver
      - eurekaserver
      - mongodb-eureka
    deploy: 
      restart_policy:
        condition: on-failure
        delay: 35s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9000/eureka/
      MONGODB_HOST_NAME: mongodb-eureka
  card:
    image: pisethbank/card:latest
    mem_limit: 700m
    ports:
      - "5000:8070"
    networks:
      - pisethbanknet
    depends_on:
      - configserver
      - eurekaserver
      - mongodb-eureka
    deploy: 
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9000/eureka/
      MONGODB_HOST_NAME: mongodb-eureka
networks:
  pisethbanknet: