account.msg = Welcome to the piseth Bank account Dev application GitHub config private
account.build-version=1

account.mailDetails.hostName=dev-account@piseth.com
account.mailDetails.port=8888
account.mailDetails.from={cipher}32dddd84c8f2cb084627c9ed2b084543d62b7f1d52523c8a912ca2158318bce2259334aaabadbacb66e3feb7037a7ab2
account.mailDetails.subject=Your Account Details from Piseth Bank Dev Environment

account.activeBranches[0]=Kompong Thom
account.activeBranches[1]=Kompong Cham
account.activeBranches[2]=Preah Vihear
