account.msg = Welcome to the piseth Bank account Production application GitHub config private
account.build-version=2

account.mailDetails.hostName=prod-account@piseth.com
account.mailDetails.port=9002
account.mailDetails.from=default-account@piseth.com
account.mailDetails.subject=Your Account Details from Piseth Bank Prod Environment

account.activeBranches[0]=Kandal
account.activeBranches[1]=Banteay Mean Chey
account.activeBranches[2]=Svay Reing
