card.msg = Welcome to the piseth Bank card Production application GitHub config private
card.build-version=2

card.mailDetails.hostName=prod-card@piseth.com
card.mailDetails.port=9002
card.mailDetails.from=default-card@piseth.com
card.mailDetails.subject=Your card Details from Piseth Bank Prod Environment

card.activeBranches[0]=Kandal
card.activeBranches[1]=Banteay Mean Chey
card.activeBranches[2]=Svay Reing
