card.msg = Welcome to the piseth Bank card Dev application GitHub config private
card.build-version=1

card.mailDetails.hostName=dev-card@piseth.com
card.mailDetails.port=8888
card.mailDetails.from={cipher}32dddd84c8f2cb084627c9ed2b084543d62b7f1d52523c8a912ca2158318bce2259334aaabadbacb66e3feb7037a7ab2
card.mailDetails.subject=Your card Details from Piseth Bank Dev Environment

card.activeBranches[0]=Kompong Thom
card.activeBranches[1]=Kompong Cham
card.activeBranches[2]=Preah Vihear
