spring.application.name=loan

#spring.data.mongodb.host=mongodb-eureka
spring.data.mongodb.host=${MONGODB_HOST_NAME:localhost}
spring.data.mongodb.port=27017
spring.data.mongodb.database=loan_service
spring.data.mongodb.username=root
spring.data.mongodb.password=root
spring.data.mongodb.authentication-database=admin
server.port=8090
#logging.level.root=INFO
#logging.level.com.piseth.bank=DEBUG

#======== Shut Down Service Config =========
management.endpoint.shutdown.enabled=true

# ======== Config Server =======
spring.profiles.active=prod
#spring.config.import=configserver:http://localhost:8071
spring.config.import=optional:configserver:http://configserver:8071
#spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8071}

# ====== Eureka Register  =======
eureka.instance.preferIpAddress=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone= http://localhost:9000/eureka/

# ====== Actuator Config =========
management.endpoints.web.exposure.include=*

management.health.liveness-state.enabled=true
management.health.readiness-state.enabled=true
management.endpoint.health.probes.enabled=true

# ======== Metrics =======
management.metrics.tags.application=${spring.application.name}

# ======== Spring Rabbit MQ =======
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

# ======== configuring info endpoint =========
info.app.name = Loan Microservice
info.app.description = Piseth Bank Account App
info.app.version = 1.0.0
management.info.env.enabled = true

#====== log debug =============
logging.level.com.piset.bank.loan=DEBUG

#========= Open Telemetry ==============
logging.pattern.level="%5p [${spring.application.name},%X{trace_id},%X{span_id}]"