spring.application.name=message
server.port=9010


# ======== Spring Rabbit MQ =======
spring.cloud.function.definition=email|sms
spring.cloud.stream.bindings.emailsms-in-0.destination=send-communication
spring.cloud.stream.bindings.emailsms-in-0.group=${spring.application.name}

spring.cloud.stream.bindings.emailsms-out-0.destination=communication-send
spring.cloud.stream.bindings.emailsms-out-0.group=${spring.application.name}

#spring.cloud.stream.kafka.binder.brokers=localhost:9092,localhost:9094,localhost:9096
spring.cloud.stream.kafka.binder.brokers=kafka-broker-1:9092,kafka-broker-2:9094,kafka-broker-3:9096

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.connection-timeout=10s